### ISSUE TITLE
[Guide] FreeBSD 10 - installing libv8 (3.16.14.7).

### ISSUE THREAD

**Issue by perlporter** [gitlabhq/gitlab-recipes#287]
I am following the instructions for installing GITLAB on FreeBSD [1] and found the following error:

https://gist.github.com/anonymous/a6d58f6618b9871f619f79c51f87aa81

Could anyone tell me how to proceed in this case?

[1] - https://github.com/gitlabhq/gitlab-recipes/blob/master/install/freebsd/freebsd-10.md

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Comment by axilleas** [comment]
Hey @perlporter, did you know there is a FreeBSD package https://www.freshports.org/www/gitlab? You might want to try that.
